### ISSUE TITLE
Floating dependency versions

### ISSUE THREAD

**Issue by commonquail** [foucault/nvfancontrol#20]
The following dependencies in `master` as of 0f642a6a9c8c14b50d97325d08ec0487d226a49b use only wildcards:

- `getopts`
- `time`
- `dirs`
- `nix`
- `ctrlc`

Another 5 are pinned to exact versions.

> > the floating versions on master `make` this kind of harder that it should be
>
> Effectively impossible. I was going to submit another change to pin the remaining dependency versions for precisely that reason but hadn't gotten to it yet. Why do you want to avoid that?
>
> _Originally posted by @commonquail in https://github.com/foucault/nvfancontrol/pull/19#issuecomment-613664863_

Apparently all versions are pinned in the two `release-*` branches.

Over time, this is liable to invite breakage of `master` by incompatibilities introduced in new versions of the unpinned dependencies; and relative to to the README this has already happened with `getopts` v0.2.20 and `libloading` v0.6.0.

It's unclear if this is an oversight or deliberate, and if so, what the motivation behind is.

**Comment by foucault** [comment]
You're probably correct. In the longer term it's better to keep dependencies manageable. There's lots of breakage going around with rust libraries so at least this also keeps master buildable. Dependencies can be updated later when/if needed.
