### ISSUE TITLE
XNVCtrl failed: XOpenDisplay failed; is $DISPLAY set?

### ISSUE THREAD

**Issue by GMonster0905** [foucault/nvfancontrol#26]
When I run the bin file, one error reported ,I have create the file named 20-nvidia.conf in /usr/share/X11/xorg.conf.d/.
distro: ubuntu 18.04

**Comment by foucault** [comment]
Closed due to inactivity and insufficient information. Please reopen if necessary.

**Comment by recolic** [comment]
Hi, why I need a DISPLAY to adjust the GPU fan speed...
Most linux GPU server have no display at all.

**Comment by foucault** [comment]
Unfortunately that's the way it works with the NVidia driver. It assumes the presence of a display server to do anything with their NVCtrl API. Some workarounds [may exist](https://github.com/foucault/nvfancontrol/issues/11#issuecomment-508776724) but they are orthogonal to nvfancontrol.
