### ISSUE TITLE
please provide a windows build

### ISSUE THREAD

**Issue by jdestefx** [foucault/nvfancontrol#27]
please provide a windows build.  not everyone has the time or knowledge to compile this.  why not just provide a download?

**Comment by foucault** [comment]
Hi! There are builds ready to download in the [releases page](https://github.com/foucault/nvfancontrol/releases). The RTX branch hasn't been merged yet but you can still use an experimental build available [here](https://github.com/foucault/nvfancontrol/issues/12#issuecomment-626244082).
