### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by tris-tan** [foucault/nvfancontrol#28]
Hi, thanks for making nvfancontrol, I've been using it successfully for some months now. Very useful.

I upgraded my nvidia drivers to version 455.45.01(non-free) today and it's started crashing on launch with this message:

> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseFloatError { kind: Invalid }', src/main.rs:86:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

I'm using 5.9.10-1-MANJARO kernel and my graphics card is NVIDIA GeForce RTX 2060 SUPER. Reinstalling hasn't helped.

Help appreciated!

**Comment by foucault** [comment]
Hi! Thanks for reporting. Can you please run the binary manually with the debug flag and paste the output up to the point of crash?

`nvfancontrol -d -f`

**Comment by tris-tan** [comment]
I get basically the same message:

> [tristan@Zen ~]$ nvfancontrol -d -f
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseFloatError { kind: Invalid }', src/main.rs:86:34
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by foucault** [comment]
If you're using the standard 0.4.1 version this is now addressed in master. I'll draft a new release shortly so if you're using AUR it will be there soon.

**Comment by tris-tan** [comment]
Amazing, thank you!
