### ISSUE TITLE
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found

### ISSUE THREAD

**Issue by jhgoodwin** [foucault/nvfancontrol#30]
I used to be able to run the nvfancontrol.service. I had a minor issue where I couldn't seem to get it to run properly on startup, so I would just rerun it after logging in.

After a long vacation, I got back home and it wouldn't start (probably after an update).

So I looked for an update to nvfancontrol.service and saw you released 0.50, so I downloaded and ran that. Now I get a new error. Do you have a suggestion how to most easily fix this? I'm fine with co-locating the dependencies with your application to minimize breakage other places in my system.

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```
```
$ systemctl --user status nvfancontrol.service 
● nvfancontrol.service - "NVIDIA Dynamic fan control"
     Loaded: loaded (/home/jhgoodwin/.config/systemd/user/nvfancontrol.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Mon 2021-01-25 10:32:15 EST; 7s ago
    Process: 7436 ExecStart=/home/jhgoodwin/.config/systemd/user/nvfancontrol (code=exited, status=1/FAILURE)
   Main PID: 7436 (code=exited, status=1/FAILURE)

Jan 25 10:32:15 jhg-R3700X systemd[2853]: Started "NVIDIA Dynamic fan control".
Jan 25 10:32:15 jhg-R3700X nvfancontrol[7436]: /home/jhgoodwin/.config/systemd/user/nvfancontrol: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/jhgoodwin/.config/systemd/user/nvfancontrol)
Jan 25 10:32:15 jhg-R3700X systemd[2853]: nvfancontrol.service: Main process exited, code=exited, status=1/FAILURE
Jan 25 10:32:15 jhg-R3700X systemd[2853]: nvfancontrol.service: Failed with result 'exit-code'.
```

I saw some other person in a different forum mentioned using the LD_LIBRARY_PATH to pin a version that was downloaded. I wanted to see what you suggest before doing weird stuff to fix it.

John

**Comment by foucault** [comment]
Hi! Your glibc is probably older than 2.32. The obvious solution is to build it yourself, it's a relatively straightforward procedure (see [here](https://github.com/foucault/nvfancontrol#building)) You only need libXNVCtrl, libXlib, libXext and of course a Rust compiler. All should be available from the Ubuntu repositories. The long-term solution is me doing builds in an isolated environment, preferably with glibc 2.27 or thereabouts. Unfortunately glibc is the only dependency we cannot reliably vendor.

**Comment by foucault** [comment]
OK so I rebuilt it in an ubuntu bionic environment. Could you please check if it works for you?


[nvfancontrol-0.5.0.tar.gz](https://github.com/foucault/nvfancontrol/files/5868116/nvfancontrol-0.5.0.tar.gz)

**Comment by jhgoodwin** [comment]
Yes, it works great!
Thanks so much.
Thanks for making this project by the way. The auto spin up/down on my fan for whatever reason doesn't work great so I get a click as it spins down and starts back up. It drives me absolutely batty. Your project is saving sanity cells! :smile:

**Comment by foucault** [comment]
Great! That's good to know. I will update the existing linux binary with the one targeting GLIBC_2.27. Hopefully it's "good enough" for most cases. Again, the linux binaries are mostly provided for convenience; ideally I should provide some ubuntu/debian packages to avoid these issues. Maybe in the future.
