### ISSUE TITLE
XNVCtrl SetAttr(THERMAL_COOLER_LEVEL) failed

### ISSUE THREAD

**Issue by Project0** [foucault/nvfancontrol#31]
Not sure what is the problem here, just recently updated my (arch linux) system and it stopped working
The only relation i can see is the jump of the nvidia driver from 460 to 465.

```
nvfancontrol -d
WARN - No config file found; using default curve
DEBUG - Default configuration loaded
DEBUG - [[gpu]]
id = 0
enabled = true
points = [[41, 20], [49, 30], [57, 45], [66, 55], [75, 63], [78, 72], [80, 80]]
DEBUG - Curve points: [(41, 20), (49, 30), (57, 45), (66, 55), (75, 63), (78, 72), (80, 80)]
INFO - NVIDIA driver version: 465.24.02
INFO - NVIDIA graphics adapter #0: NVIDIA GeForce GTX 1070
INFO -   GPU #0 coolers: COOLER-0
ERROR - Could not update fan speed: XNVCtrl SetAttr(THERMAL_COOLER_LEVEL) failed; error 0
```

**Comment by foucault** [comment]
Hello! There are literally no differences in XNVCtrl (the NVIDIA interface library) between 460.xx and 465.xx so this shouldn't happen. Can you please verify that your xorg.conf is indeed correct?

**Comment by jlarmstrong** [comment]
Just confirming here that I am also seeing this issue in the latest 460.73.1 release.

**Comment by foucault** [comment]
Possibly some of the code in 465 was backported into the 460 branch. I highly doubt we'll see any fix for that until 470.

**Comment by vandonsel** [comment]
I am able to set fan speed in nvidia-settings and I am also getting a very similar error. Please inform me if this warrants a new ticket: `[d@virtlove ~]$ nvfancontrol -d
INFO - Loading configuration file: "/home/d/.config/nvfancontrol.conf"
DEBUG - Curve points: [(30, 20), (40, 30), (50, 50), (60, 70), (70, 100)]
INFO - NVIDIA driver version: 465.24.02
INFO - NVIDIA graphics adapter #0: NVIDIA GeForce GTX 1050 Ti
INFO -   GPU #0 coolers: COOLER-0
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "XNVCtrl QueryAttr(COOLER_SPEED) failed; error 0"', src/main.rs:715:59
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
DEBUG - Resetting fan control`

**Comment by foucault** [comment]
Try putting nvfancontrol in monitor mode (`nvfancontrol -d -m`) and change the values from nvidia-settings. Is there any change in the output of nvfancontrol?

**Comment by vandonsel** [comment]
Looks like I get the same error running it with those arguments

> [d@virtlove ~]$ nvfancontrol -d -m
INFO - Loading configuration file: "/home/d/.config/nvfancontrol.conf"
DEBUG - Curve points: [(30, 20), (40, 30), (50, 50), (60, 70), (70, 100)]
INFO - NVIDIA driver version: 465.27
INFO - NVIDIA graphics adapter #0: NVIDIA GeForce GTX 1050 Ti
INFO -   GPU #0 coolers: COOLER-0
INFO - Option "-m" is present; curve will have no actual effect
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "XNVCtrl QueryAttr(COOLER_SPEED) failed; error 0"', src/main.rs:715:59
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by reytiger** [comment]
I experienced `ERROR - Could not update fan speed: XNVCtrl SetAttr(THERMAL_COOLER_LEVEL) failed; error 0` on Arch Linux and found I could not alter fan settings in nvidia-settings.

Kernel: 5.12.6-arch1-1
Driver: nvidia 465.31-4
Util:   nvidia-settings 465.27-1

Following [these steps](https://github.com/NVIDIA/nvidia-settings/issues/65#issuecomment-833096064) fixed my issue, indicating this was a configuration/permissions problem for rootless Xorg.

**Comment by foucault** [comment]
It's a shame that you need to run X as root to make this work. But in any case this is not an `nvfancontrol` bug. Thanks for reporting and investigating !
