### ISSUE TITLE
Add Cargo.lock for nix packaging

### ISSUE THREAD

**Issue by devins2518** [foucault/nvfancontrol#34]
Hi, I'm currently trying to package this for NixOS, and it needs the Cargo.lock file available to produce reproducible binaries. Could you please remove the Cargo.lock file from the gitignore?

**Comment by foucault** [comment]
I'd rather not do that in the main repository unless there is a compelling reason to do so. The working branch of the repository should be buildable but not necessarily reproducible. What I could possibly do is attach the latest Cargo.lock used to generate a release either along the release artifacts (like [this](https://github.com/foucault/nvfancontrol/releases/download/0.5.1/Cargo.lock)), or in the release-specific branch. Would either one of those work?

**Comment by devins2518** [comment]
A release specific branch would be a better choice I'm thinking

**Comment by foucault** [comment]
Starting from the `release-0.5.0` branch lock files are now included.
