### ISSUE TITLE
Limits not working?

### ISSUE THREAD

**Issue by marc1uk** [foucault/nvfancontrol#38]
i have driver version 390, no particular warnings emitted, but it seems like I still can't override the fan limits.
My config:
```
cat ~/.config/nvfancontrol.conf
10 0
30 0
60 0
65 50
80 80
```

when I try to run it:
```
$ ./nvfancontrol -d -f -l 0
INFO - Loading configuration file: "/home/marc/.config/nvfancontrol.conf"
DEBUG - Curve points: [(10, 0), (30, 0), (60, 0), (65, 50), (80, 80)]
INFO - NVIDIA driver version: 390.138
INFO - NVIDIA graphics adapter #0: GeForce GTX 580
INFO -   GPU #0 coolers: COOLER-0
DEBUG - Temp: 45; Speed: [1260] RPM ([18]%); Load: 0%; Mode: Manual
DEBUG - Temp: 45; Speed: [1230] RPM ([17]%); Load: 0%; Mode: Manual

```

So it still seems to idle at 17%. If i use the nvidia server settings to set the speed down to 10%, it applies, but anything below 10% does nothing. Any ideas?

**Comment by foucault** [comment]
Hello! This looks normal. Regardless what you set the limits to, it's still dependent on the card's firmware. Some cards support turning off the fans. In that case just remove the 0 entries from your configuration and the fans will switch off below the cutoff temperature, or the first configured temperature in your config (whatever is lower). Some other cards do not support that and in that case regardless the actual value or the configured limit the actual minimum fan speed is capped.

18 Nov 2021 02:16:59 marc1uk ***@***.***>:

**Comment by marc1uk** [comment]
Ah drat, I was hoping that wasn't the case, I guess I'll just try things the hardware way :smile: :wrench: . Thanks for the quick reply.
