### ISSUE TITLE
Fan is enabled on auto control; doing nothing

### ISSUE THREAD

**Issue by ng0177** [foucault/nvfancontrol#39]
Followed instructions closely on
```
Description:	EndeavourOS Linux
5.15.7-arch1-1
x11
```
but
```
msi: ~ $ nvfancontrol -d -l 0
INFO - Loading configuration file: "/home/k7ara/.config/nvfancontrol.conf"
DEBUG - Curve points: [(20, 0), (30, 0), (40, 20), (50, 45), (60, 55), (70, 70), (80, 80)]
INFO - NVIDIA driver version: 495.44
INFO - NVIDIA graphics adapter #0: NVIDIA GeForce GTX 1060 6GB
INFO -   GPU #0 coolers: COOLER-0
DEBUG - Fan is enabled on auto control; doing nothing
DEBUG - Temp: 26; Speed: [1043] RPM ([35]%); Load: 0%; Mode: Auto
DEBUG - Fan is enabled on auto control; doing nothing
DEBUG - Temp: 25; Speed: [1039] RPM ([35]%); Load: 0%; Mode: Auto
DEBUG - Fan is enabled on auto control; doing nothing
```

**Comment by foucault** [comment]
This looks normal. Further down in the README there is this bit

> In addition, note that the program by default will not use the custom curve if the fan is already spinning in automatic control. This is the most conservative configuration for GPUs that turn their fans off below a certain temperature threshold. If you want to always use the custom curve pass the additional `-f` or `--force` argument.

nvfancontrol is by default very conservative. When the fan is already spinning during startup the fan _will not_ be applied as it might be controlled by a different program, or to avoid overheating the card.  Try passing the `-f` argument to force-apply the curve.

Please note that depending on the GPU firmware it might not be possible to turn the fan off.

**Comment by ng0177** [comment]
Yes, looks like it is not possible. If I have to turn it off, is the only option to cut wires with pliers then?
```
msi: ~ $ nvfancontrol -f -d -l 0
INFO - Loading configuration file: "/home/k7ara/.config/nvfancontrol.conf"
DEBUG - Curve points: [(20, 0), (30, 0), (40, 20), (50, 45), (60, 55), (70, 70), (80, 80)]
INFO - NVIDIA driver version: 495.44
INFO - NVIDIA graphics adapter #0: NVIDIA GeForce GTX 1060 6GB
INFO -   GPU #0 coolers: COOLER-0
DEBUG - Temp: 26; Speed: [1045] RPM ([35]%); Load: 0%; Mode: Manual
DEBUG - Temp: 26; Speed: [1038] RPM ([35]%); Load: 0%; Mode: Manual
```

**Comment by foucault** [comment]
Unfortunately is not something nvfancontrol can help with. It's most probably hardwired into the card's firmware.
