### ISSUE TITLE
Why does limitation 20..80% exists?

### ISSUE THREAD

**Issue by nazar-pc** [foucault/nvfancontrol#4]
> Bear in mind that for most GPUs the fan speed can't be below 20% or above 80% when in manual control, even if you use greater values.

Can you elaborate why? I can easily set any level manually below 20% in NVIDIA X Server Settings (including 0%) as well as 100% (GPU is GIGABYTE GTX 1070 G1 Gaming). But this tool still limits its lower limit to 20%.

The default curve in my GPU is like `[(0, 0), (51, 0), (52, 28), (90, 100)]`, but I want to change it to `[(0, 0), (60, 0), (61, 25), (90, 100)]`.

```
 nazar-pc  ~  nvfancoltrol  ./nvfancontrol -f -d                                                                                                                                                                                       
DEBUG - Curve points: [(0, 0), (60, 0), (61, 25), (90, 100)]
Using NVIDIA driver version 375.20
DEBUG - Temp: 49; Speed: 800 RPM (19%); Load: 6%; Mode: Manual
DEBUG - Temp: 49; Speed: 821 RPM (20%); Load: 3%; Mode: Manual
DEBUG - Temp: 49; Speed: 835 RPM (20%); Load: 3%; Mode: Manual
DEBUG - Temp: 49; Speed: 836 RPM (20%); Load: 8%; Mode: Manual
DEBUG - Temp: 49; Speed: 842 RPM (20%); Load: 8%; Mode: Manual
DEBUG - Temp: 49; Speed: 838 RPM (20%); Load: 4%; Mode: Manual
```

**Comment by foucault** [comment]
This is probably a limitation of the driver; I don't know whether this is an actual hardware limitation or a hard-coded minimum value of XNVCtrl. The program always sends the preferred fan speed to the driver and reports back the value the driver has actually set. I am fairly sure that below a threshold is impossible to actually spin the fan reliably. If you put a low value, eg. 5% or 10%, in nvidia-settings you will see that the fan momentarily spins on at an undefined value, usually 500-900 RPM and then spins down again (0 RPM). Depending on the card vendor these boundaries might be more relaxed. In my 960 and 1060 the usable range is 19-82%.
