### ISSUE TITLE
Fans still work despite being forced & had aggressive idle mode

### ISSUE THREAD

**Issue by pc00per** [foucault/nvfancontrol#40]
```
[cooper@arch ~]$ nvfancontrol -fd
INFO - Loading configuration file: "/home/cooper/.config/nvfancontrol.conf"
DEBUG - Curve points: [(60, 0), (65, 20), (70, 40), (75, 60), (80, 80), (85, 100)]
INFO - NVIDIA driver version: 510.60.02
INFO - NVIDIA graphics adapter #0: NVIDIA GeForce GTX 1660 SUPER
INFO -   GPU #0 coolers: COOLER-0
DEBUG - Temp: 54; Speed: [0] RPM ([0]%); Load: 23%; Mode: Auto
DEBUG - Temp: 54; Speed: [871] RPM ([26]%); Load: 21%; Mode: Auto
DEBUG - Temp: 54; Speed: [0] RPM ([0]%); Load: 20%; Mode: Auto
DEBUG - Temp: 54; Speed: [868] RPM ([26]%); Load: 20%; Mode: Auto
DEBUG - Temp: 54; Speed: [0] RPM ([0]%); Load: 21%; Mode: Auto
DEBUG - Temp: 54; Speed: [0] RPM ([0]%); Load: 20%; Mode: Auto
DEBUG - Temp: 54; Speed: [0] RPM ([0]%); Load: 20%; Mode: Auto
DEBUG - Temp: 54; Speed: [805] RPM ([24]%); Load: 21%; Mode: Auto
DEBUG - Temp: 54; Speed: [844] RPM ([26]%); Load: 21%; Mode: Auto
DEBUG - Temp: 54; Speed: [0] RPM ([0]%); Load: 21%; Mode: Auto
DEBUG - Temp: 54; Speed: [0] RPM ([0]%); Load: 20%; Mode: Auto
DEBUG - Temp: 54; Speed: [0] RPM ([0]%); Load: 20%; Mode: Auto
DEBUG - Temp: 54; Speed: [0] RPM ([0]%); Load: 20%; Mode: Auto
DEBUG - Temp: 54; Speed: [0] RPM ([0]%); Load: 20%; Mode: Auto
DEBUG - Temp: 54; Speed: [0] RPM ([0]%); Load: 20%; Mode: Auto
DEBUG - Temp: 56; Speed: [0] RPM ([0]%); Load: 7%; Mode: Auto
DEBUG - Temp: 55; Speed: [0] RPM ([0]%); Load: 32%; Mode: Auto
DEBUG - Temp: 55; Speed: [0] RPM ([0]%); Load: 29%; Mode: Auto
DEBUG - Temp: 55; Speed: [831] RPM ([25]%); Load: 8%; Mode: Auto
DEBUG - Temp: 56; Speed: [853] RPM ([26]%); Load: 11%; Mode: Auto
DEBUG - Temp: 56; Speed: [0] RPM ([0]%); Load: 1%; Mode: Auto
```
Is there anyway to disable autocontrol? It's GTX 1660S & also has beefy cooler that can even handle constant 60 degrees on idle.

**Comment by pc00per** [comment]
Will try & let you know. And about the xorg, I thought it only need for coolbits. Will also try to run xorg on root & check it again.
Btw I'm not interested in OC anyways.

**Comment by pc00per** [comment]
@foucault Btw tnx for mentioning. xorg does run as root on my machine. But nvfancontrol wasn't, as I was running without previliges. After rooted execution, mode turned into manual & I can see the default points work perfectly
```
points = [[41, 20], [49, 30], [57, 45], [66, 55], [75, 63], [78, 72], [80, 80]]
DEBUG - Curve points: [(41, 20), (49, 30), (57, 45), (66, 55), (75, 63), (78, 72), (80, 80)]
```
Can I know which is the default config under /etc ? Will make my changes directly there, as non-rooted mode seems to not work for me.

**Comment by foucault** [comment]
Technically you shouldn't need to run it as root but this might have changed in recent driver revisions. The default fan curve should be located in `/etc/xdg/nvfancontrol.conf`.

**Comment by pc00per** [comment]
> Technically you shouldn't need to run it as root but this might have changed in recent driver revisions. The system-wide fan curve should be located in `/etc/xdg/nvfancontrol.conf`.

Got it. But my main aim right now, is to keep the fans to 0 at idle (<60c). Any workaround for it?
I've tried to go below 60. Upto 53c - 0% It works. But when on  54c - 0%, manual mode turns into auto mode & Nvctl takes over.

**Comment by ghost** [comment]
I kinda left fan control completely. Whatever I do, fans never sit idle.
