### ISSUE TITLE
Fan control only sets the speed of one fan

### ISSUE THREAD

**Issue by LPAiken** [foucault/nvfancontrol#9]
I have an MSI RTX 2070 that has two fans, however, the controller only sets the fan speed of one of the fans (Fan 1 according to the nvidia-settings GUI) and leaves the other fan (Fan 0) at 0.  Is there any easy fix to this?
![nvidia-settings](https://user-images.githubusercontent.com/32507269/57431611-a219a900-7233-11e9-9f62-07d9c606e37c.jpg)

**Comment by LPAiken** [comment]
Absolutely, just let me know what I can do!

**Comment by foucault** [comment]
So [the attached program](https://github.com/foucault/nvfancontrol/files/3164183/enumerate.gz) will enumerate GPUs and list (among other things) the coolers of each one. It needs a relatively recent NVIDIA driver. I've precompiled it for x86-64. You will need to decompress it first (`gunzip enumerate.gz`) and then run it (`./enumerate`). In case you need to compile it yourself you can do so with
```
gcc -Wall -lX11 -lXext -I /usr/include/NVCtrl nv-control-targets.c /usr/lib/libXNVCtrl.a -o enumerate
```
using the code from [here](https://gist.github.com/foucault/a392de6e83786e70cd6041ca5b2cdba3). If you do so you might need to adjust the path of `libXNVCtrl.a` depending on your distribution. In any case can you please provide me with its output?

**Comment by LPAiken** [comment]
Here you go.  Just so you know, I have a 2080 Ti Founder's Edition that is water-cooled and is not connected to any screens (I do a lot of machine learning).  The 2070 is air-cooled and runs my two monitors.  It is an [MSI RTX 2070 Armor](https://www.msi.com/Graphics-card/GeForce-RTX-2070-ARMOR-8G-OC) in case that matters.  Here is the output of the program:

Using NV-CONTROL extension 1.29 on :0

Server System Information:

  number of GPUs: 2
  number of X Screens: 1
  number of display devices: 16 (DPY-0, DPY-1, DPY-2, DPY-3, DPY-4, DPY-5, DPY-6, DPY-7, DPY-8, DPY-9, DPY-10, DPY-11, DPY-12, DPY-13, DPY-14, DPY-15)
  number of Frame Lock Devices: 0
  number of Visual Computing System Devices: 0
  number of Graphics Video Input Devices: 0
  number of Cooler Devices: 4
  number of Thermal Sensor Devices: 2


GPU 0 information:
   Product Name                    : GeForce RTX 2070
   GPU UUID                        : GPU-60dc5036-03d1-623f-a89f-204259f4aaab
   Coolers on GPU                  : COOLER-1, COOLER-0 [len = 12]
   Thermal Sensors on GPU          : THERMAL-SENSOR-0
   Connected Display Devices       : DPY-0, DPY-3
   Framelock Devices               : 
   Number of X Screens on GPU 0    : 1

   X Screen 0 information:
       Assigned Display Devices    : DPY-0, DPY-1, DPY-2, DPY-3, DPY-4, DPY-5, DPY-6, DPY-7
       Enabled Display Devices     : DPY-0, DPY-3


GPU 1 information:
   Product Name                    : GeForce RTX 2080 Ti
   GPU UUID                        : GPU-ace0e83a-78b0-7f8b-2377-cd2fb5a9708e
   Coolers on GPU                  : COOLER-3, COOLER-2 [len = 12]
   Thermal Sensors on GPU          : THERMAL-SENSOR-1
   Connected Display Devices       : 
   Framelock Devices               : 
   Number of X Screens on GPU 1    : 0

**Comment by foucault** [comment]
Great, so the coolers are numbered sequentially and have a unique identifier. Is the id of each cooler fixed or randomized during each run or boot? If not it should be pretty straightforward to fix.

**Comment by LPAiken** [comment]
For me, GPU 0 and GPU 1 are always the same for me, but I don't know if this is a hard and fast rule.  I think I would have noticed a swap because I have to set which GPU gets used in my code.  I rebooted a few times and there was no change.

**Comment by foucault** [comment]
I think I made some progress. Now the curve should be applied to all of the fans of the GPU. As it is now this applies to a single GPU, although it shouldn't be much effort to make it work for all GPUs (possibly with different curves). [I've attached a build](https://github.com/foucault/nvfancontrol/files/3170410/nvfancontrol.gz) with these changes (`gunzip` it first). Or if you want to build it from source you can [apply this patch](https://gist.github.com/foucault/ef11a1c01e2cc834678eea9f201f8481) instead.

First you can try running with the `-p` switch which should list the available GPUs and coolers not dissimilar to what the program I've attached before did. The ids should hopefully be the same.

Then you can try running the actual program like so
```
./nvfancontrol -d -f -g 0
```
Adjust the `-g` option to apply to different GPUs if you want. From what I've seen GPU 0 should be the 2070. Let it run for a minute or so and let me know if both GPU coolers are being adjusted.  In any case, please paste the output of `nvfancontrol`.

**Comment by LPAiken** [comment]
It appears to work beautifully.  If you need me to do anymore testing for you, I would be happy to test it out for you.  Here is some of the output you requested:

DEBUG - Curve points: [(30, 35), (40, 40), (50, 55), (60, 65), (70, 80), (80, 100)]
INFO - NVIDIA driver version: 418.56
INFO - NVIDIA graphics adapter #0: GeForce RTX 2070
INFO -   GPU #0 coolers: COOLER-1, COOLER-0
INFO - NVIDIA graphics adapter #1: GeForce RTX 2080 Ti
INFO -   GPU #1 coolers: COOLER-3, COOLER-2
DEBUG - Temp: 35; Speed: [0, 0] RPM ([0, 0]%); Load: 8%; Mode: Manual
DEBUG - Temp: 35; Speed: [1390, 1386] RPM ([53, 53]%); Load: 11%; Mode: Manual
DEBUG - Temp: 35; Speed: [792, 806] RPM ([30, 31]%); Load: 8%; Mode: Manual
DEBUG - Temp: 35; Speed: [1027, 1014] RPM ([40, 39]%); Load: 12%; Mode: Manual
DEBUG - Temp: 35; Speed: [948, 962] RPM ([36, 37]%); Load: 8%; Mode: Manual
DEBUG - Temp: 35; Speed: [955, 946] RPM ([37, 36]%); Load: 9%; Mode: Manual
DEBUG - Temp: 35; Speed: [972, 973] RPM ([37, 37]%); Load: 9%; Mode: Manual
DEBUG - Temp: 35; Speed: [954, 949] RPM ([37, 37]%); Load: 9%; Mode: Manual
DEBUG - Temp: 35; Speed: [972, 972] RPM ([37, 37]%); Load: 12%; Mode: Manual
DEBUG - Temp: 35; Speed: [957, 953] RPM ([37, 37]%); Load: 11%; Mode: Manual
DEBUG - Temp: 35; Speed: [966, 959] RPM ([37, 37]%); Load: 14%; Mode: Manual
DEBUG - Temp: 35; Speed: [964, 966] RPM ([37, 37]%); Load: 10%; Mode: Manual
DEBUG - Temp: 35; Speed: [956, 967] RPM ([37, 37]%); Load: 14%; Mode: Manual
DEBUG - Temp: 35; Speed: [963, 965] RPM ([37, 37]%); Load: 13%; Mode: Manual
DEBUG - Temp: 35; Speed: [966, 955] RPM ([37, 37]%); Load: 14%; Mode: Manual
DEBUG - Temp: 34; Speed: [965, 965] RPM ([37, 37]%); Load: 12%; Mode: Manual
DEBUG - Temp: 34; Speed: [960, 966] RPM ([37, 37]%); Load: 12%; Mode: Manual
DEBUG - Temp: 34; Speed: [956, 962] RPM ([37, 37]%); Load: 10%; Mode: Manual
DEBUG - Temp: 34; Speed: [959, 961] RPM ([37, 37]%); Load: 8%; Mode: Manual
DEBUG - Temp: 34; Speed: [968, 956] RPM ([37, 37]%); Load: 8%; Mode: Manual
DEBUG - Temp: 34; Speed: [964, 960] RPM ([37, 37]%); Load: 9%; Mode: Manual
DEBUG - Temp: 34; Speed: [955, 958] RPM ([37, 37]%); Load: 9%; Mode: Manual
DEBUG - Temp: 34; Speed: [960, 956] RPM ([37, 37]%); Load: 8%; Mode: Manual
DEBUG - Temp: 34; Speed: [962, 956] RPM ([37, 37]%); Load: 8%; Mode: Manual
DEBUG - Temp: 34; Speed: [967, 960] RPM ([37, 37]%); Load: 13%; Mode: Manual
DEBUG - Temp: 34; Speed: [965, 964] RPM ([37, 37]%); Load: 12%; Mode: Manual
DEBUG - Temp: 34; Speed: [966, 959] RPM ([37, 37]%); Load: 10%; Mode: Manual
DEBUG - Temp: 34; Speed: [961, 963] RPM ([37, 37]%); Load: 11%; Mode: Manual
DEBUG - Temp: 34; Speed: [959, 959] RPM ([37, 37]%); Load: 8%; Mode: Manual
DEBUG - Temp: 34; Speed: [954, 958] RPM ([37, 37]%); Load: 12%; Mode: Manual
DEBUG - Temp: 34; Speed: [960, 965] RPM ([37, 37]%); Load: 6%; Mode: Manual
DEBUG - Temp: 34; Speed: [967, 964] RPM ([37, 37]%); Load: 3%; Mode: Manual
DEBUG - Temp: 34; Speed: [962, 953] RPM ([37, 37]%); Load: 4%; Mode: Manual
DEBUG - Temp: 34; Speed: [959, 969] RPM ([37, 37]%); Load: 12%; Mode: Manual
DEBUG - Temp: 34; Speed: [956, 964] RPM ([37, 37]%); Load: 12%; Mode: Manual
DEBUG - Temp: 34; Speed: [959, 962] RPM ([37, 37]%); Load: 9%; Mode: Manual
DEBUG - Temp: 34; Speed: [961, 960] RPM ([37, 37]%); Load: 8%; Mode: Manual
DEBUG - Temp: 34; Speed: [962, 955] RPM ([37, 37]%); Load: 8%; Mode: Manual

**Comment by foucault** [comment]
Great, that's good to hear! Could you please verify with `nvidia-settings` that the settings are indeed applied to the correct GPU and coolers?

**Comment by LPAiken** [comment]
Yup!  Everything is working beautifully.  Thank you so much!
![nvidia-settings-2](https://user-images.githubusercontent.com/32507269/57587851-2efe8400-750c-11e9-8476-77bddaf77800.jpg)
